### ISSUE TITLE
New-Object : Cannot find type [MediaInfoNET]: verify that the assembly containing this type is loaded.

### ISSUE THREAD

**Issue by baal77** [stax76/Get-MediaInfo#2] opened 2020-05-01 21:27 UTC
Hello Stax !

Thanks for this new version !
It works perfectly on my side too !

However, by reading your code I noticed that a new test have been added concerning including of `":\"` into the `$File` variable.
It makes me thinking about another case in which it could fail that I've not tested before.

I have a NAS on which I've 2 network drives.
It works fine when I use the letter of the drive, but in PowerShell it is also reachable without the need of a Map Drive (it wasn't the case in CMD), and I wasn't sure that a `":\"` appears in the path.
But, in fact, it's the case ... so I tried.

But unfortunately, it fails.
Not same error than before ...

```
[b77@fractal] Z:\medias\videos\movies\
movies> Get-MediaInfo .\127.hours.2010.vf.vost.1080p.aac.5.1.njd.mkv


FileName       : 127.hours.2010.vf.vost.1080p.aac.5.1.njd.mkv
Ext            : mkv
Format         : AVC
DAR            : 1.846
Width          : 1920
Height         : 1040
BitRate        : 2045
Duration       : 93.706116666666674
FileSize       : 1967.1314277648926
FrameRate      : 23.976
ScanType       : Progressive
ColorPrimaries :
Transfer       :
FormatProfile  : High@L4
AudioCodec     : AC-3 / AC-3
TextFormat     : UTF-8 / UTF-8
Directory      : Z:\medias\videos\movies
```

```
[b77@fractal] Z:\medias\videos\movies\
movies> cd \\10.77.0.10\z33h\medias\videos\movies\
```

```
[b77@fractal] Microsoft.PowerShell.Core\FileSystem::\\10.77.0.10\z33h\medias\videos\movies\
movies>
```

```
movies> Get-MediaInfo .\127.hours.2010.vf.vost.1080p.aac.5.1.njd.mkv
New-Object : Cannot find type [MediaInfoNET]: verify that the assembly containing this type is loaded.
At C:\Users\b77\OneDrive\documents\powershell\includes\Get-MediaInfo\Get-MediaInfo.ps1:105 char:27
+                     $mi = New-Object MediaInfoNET -ArgumentList $File
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
```

It's much less annoying that for the bug in the current directory, as I can live without direct network paths by using the mapped drives, but perhaps it will permit to you to reproduce and analyse it.

I put at the bottom of this message the TXT from MediaInfo of this 127.hours movie, and I also put two others TXT with their videos files (one small, direct from my 2012 Sony Xperia S, and one medium which I've encode many years ago), for which your script doesn't work at all, even in local, but with EXACTLY the same error message.

```
[b77@fractal] C:\Users\b77\Downloads\
Downloads> Get-MediaInfo .\MOV_0093.mp4
New-Object : Cannot find type [MediaInfoNET]: verify that the assembly containing this type is loaded.
At C:\Users\b77\OneDrive\documents\powershell\includes\Get-MediaInfo\Get-MediaInfo.ps1:105 char:27
+                     $mi = New-Object MediaInfoNET -ArgumentList $File
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
```

```
[b77@fractal] C:\Users\b77\Downloads\
Downloads> Get-MediaInfo .\tlmvpsp.avi
New-Object : Cannot find type [MediaInfoNET]: verify that the assembly containing this type is loaded.
At C:\Users\b77\OneDrive\documents\powershell\includes\Get-MediaInfo\Get-MediaInfo.ps1:105 char:27
+                     $mi = New-Object MediaInfoNET -ArgumentList $File
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
```

Do you have the same error on your side on network drives ? Or is it still an error only on my side ?
And with these two files ?

Fred.

PS : Strangely, on my other computer (the French one), the error isn't' the same and looks really like the one of the bug before (".ctor" error message).
I don't know if it's a second bug or the same ... but OK with letter drive, NOK with full network path.

```
PS C:\Users\Fred> cd \\10.77.0.10\medias\videos\movies\                                                                 PS Microsoft.PowerShell.Core\FileSystem::\\10.77.0.10\medias\videos\movies> Get-MediaInfo .\127.hours.2010.vf.vost.1080p.aac.5.1.njd.mkv
New-Object : Exception lors de l'appel de « .ctor » avec « 1 » argument(s) : « Error MediaInfo_Open »
Au caractère C:\Users\Fred\Desktop\Get-MediaInfo\Get-MediaInfo.ps1:105 : 27
+                     $mi = New-Object MediaInfoNET -ArgumentList $File
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```

```
PS Microsoft.PowerShell.Core\FileSystem::\\10.77.0.10\medias\videos\movies> cd Z:\medias\videos\movies\
PS Z:\medias\videos\movies> Get-MediaInfo .\127.hours.2010.vf.vost.1080p.aac.5.1.njd.mkv


FileName       : 127.hours.2010.vf.vost.1080p.aac.5.1.njd.mkv
Ext            : mkv
Format         : AVC
DAR            : 1,846
Width          : 1920
Height         : 1040
BitRate        : 2045
Duration       : 93,7061166666667
FileSize       : 1967,13142776489
FrameRate      : 23,976
ScanType       : Progressive
ColorPrimaries :
Transfer       :
FormatProfile  : High@L4
AudioCodec     : AC-3 / AC-3
TextFormat     : UTF-8 / UTF-8
Directory      : Z:\medias\videos\movies
```

**Comment by stax76** [comment] 2020-05-03 12:50
Hello Fred,

thanks for the feedback. I don't have network drives but from debugging staxrip I knew a trick to get such a path anyway:

`\\localhost\c$\Users\frank\Desktop`

With that I could reproduce it and found a post suggesting to use `Convert-Path` and that seem to work better than `Resolve-Path`.

About _Cannot find type [MediaInfoNET]_, I made an improvement:

`Add-Type -Path ($PSScriptRoot + '\MediaInfoNET.dll')`

It's a little simpler and if this fails then possibly because $PSScriptRoot is $null and then it's impossible for me to find the location of MediaInfoNET.dll. Or maybe $PSScriptRoot gives a weird path that can be fixed with `Convert-Path` too. I was not able to reproduce it however.

I've uploaded 3.2.

**Comment by baal77** [comment] 2020-05-03 17:25
Hello Stax76 !

Thank you for this new version !
Tried on my two computers, in all terminal hosts I have, on files in local folders, on files in folders on mapped drive, on files in direct network path, on files in local folder (`.\file.mp4`), or in a relative folders  (`..\anotherfolder\anotherfile.mp4`) ... and EVERYTHING RUNS PERFECTLY, from everywhere to everywhere.

I think that the trick was here, use `Add-Type -Path ($PSScriptRoot + '\MediaInfoNET.dll')` instead of `Add-Type -Path ((Split-Path $PSCommandPath) + '\MediaInfoNET.dll')`, even if the result is (should be) strictly the same.

Everything is ok on my side now ...
YOU'RE THE KING.
THANK YOU.

**Comment by stax76** [comment] 2020-05-03 20:26
Hello baal77,

thanks for the great feedback and testing!

Next release has it renamed to from MediaInfoNET to MediaInfoSharp because it triggered a bug in my MediaInfo GUI MediaInfo.NET due to a name clash, after the Folder View was shown the Settings dialog fails to load, maybe time for a new MediaInfo.NET release.

**Closed as completed by stax76** 2020-05-03 20:26 UTC
